In [1]:
import numpy as np 
import pandas as pd

In [2]:
arrays = dict(np.load("transactions.npz"))
data = {k: [s.decode("utf-8") for s in v.tobytes().split(b"\x00")] if v.dtype == np.uint8 else v for k, v in arrays.items()}
departement = pd.DataFrame.from_dict(data)

In [3]:
departement['surface_locaux_industriels'] = departement['surface_locaux_industriels'].str.replace(r'{|}', '')
departement['surface_locaux_industriels'] = departement['surface_locaux_industriels'].apply(lambda x: x if isinstance(x, str) and x.strip() != '' else '0')
departement['surface_locaux_industriels'] = pd.to_numeric(departement['surface_locaux_industriels'], errors='coerce')
departement['surface_locaux_industriels'] = departement['surface_locaux_industriels'].fillna(0)
departement['surface_dependances'] = departement['surface_dependances'].str.replace(r'{|}', '')
departement['surface_dependances'] = departement['surface_dependances'].apply(lambda x: x if isinstance(x, str) and x.strip() != '' else '0')
departement['surface_dependances'] = pd.to_numeric(departement['surface_dependances'], errors='coerce')
departement['surface_dependances'] = departement['surface_dependances'].fillna(0)
departement['surface_terrains_agricoles'] = departement['surface_terrains_agricoles'].str.replace(r'{|}', '')
departement['surface_terrains_agricoles'] = departement['surface_terrains_agricoles'].apply(lambda x: x if isinstance(x, str) and x.strip() != '' else '0')
departement['surface_terrains_agricoles'] = pd.to_numeric(departement['surface_terrains_agricoles'], errors='coerce')
departement['surface_terrains_agricoles'] = departement['surface_terrains_agricoles'].fillna(0)
departement['surface_terrains_sols'] = departement['surface_terrains_sols'].str.replace(r'{|}', '')
departement['surface_terrains_sols'] = departement['surface_terrains_sols'].apply(lambda x: x if isinstance(x, str) and x.strip() != '' else '0')
departement['surface_terrains_sols'] = pd.to_numeric(departement['surface_terrains_sols'], errors='coerce')
departement['surface_terrains_sols'] = departement['surface_terrains_sols'].fillna(0)
departement['surface_terrains_nature'] = departement['surface_terrains_nature'].str.replace(r'{|}', '')
departement['surface_terrains_nature'] = departement['surface_terrains_nature'].apply(lambda x: x if isinstance(x, str) and x.strip() != '' else '0')
departement['surface_terrains_nature'] = pd.to_numeric(departement['surface_terrains_nature'], errors='coerce')
departement['surface_terrains_nature'] = departement['surface_terrains_nature'].fillna(0)

C:\Users\Kamir\AppData\Local\Temp\ipykernel_11260\2633795302.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  departement['surface_locaux_industriels'] = departement['surface_locaux_industriels'].str.replace(r'{|}', '')
C:\Users\Kamir\AppData\Local\Temp\ipykernel_11260\2633795302.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  departement['surface_dependances'] = departement['surface_dependances'].str.replace(r'{|}', '')
C:\Users\Kamir\AppData\Local\Temp\ipykernel_11260\2633795302.py:9: FutureWarning: The default value of regex will change from True to False in a future version.
  departement['surface_terrains_agricoles'] = departement['surface_terrains_agricoles'].str.replace(r'{|}', '')
C:\Users\Kamir\AppData\Local\Temp\ipykernel_11260\2633795302.py:13: FutureWarning: The default value of regex will change from True to False in a future version.
  departement['surface_terrains_sols'] = departement['surface_terrains_sols'].str.replace(r'{|}', '')
C:\Users\Kamir\AppData\Local\Temp\ipykernel_11260\2633795302.py:17: FutureWarning: The default value of regex will change from True to False in a future version.
  departement['surface_terrains_nature'] = departement['surface_terrains_nature'].str.replace(r'{|}', '')

In [6]:
departement["surface_totale"]=departement["surface_habitable"]+departement["surface_locaux_industriels"]+departement["surface_dependances"]+departement["surface_terrains_agricoles"]+departement["surface_terrains_sols"]+departement["surface_terrains_nature"]

In [7]:
departement['prix_m2']=departement['prix']/departement['surface_totale']

,id_transaction,date_transaction,prix,departement,id_ville,ville,code_postal,adresse,type_batiment,vefa,...,id_parcelle_cadastre,latitude,longitude,surface_dependances,surface_locaux_industriels,surface_terrains_agricoles,surface_terrains_sols,surface_terrains_nature,surface_totale,prix_m2
0,332948,2014-01-02,173020.0,01,202,LAGNIEU,1150,21 GR GRANDE RUE DE BULLIEZ,Maison,False,...,012020000F1248,45.899056,5.354210,0.0,0.0,0.0,0.0,0.0,72.0,2403.055556
1,328900,2014-01-02,157500.0,01,451,VIRIAT,1440,1369 RTE DE STRASBOURG,Maison,False,...,01451000ZO0158,46.236407,5.262935,0.0,0.0,0.0,0.0,0.0,103.0,1529.126214
2,326170,2014-01-02,112000.0,01,365,SAINT-JEAN-SUR-VEYLE,1290,5174 SAINT JEAN SUR VEYLE,Maison,False,...,013650000C0813,46.260087,4.918587,0.0,0.0,220.0,540.0,0.0,838.0,133.651551
3,328585,2014-01-02,197000.0,01,427,TREVOUX,1600,6346 MTE DES LILAS,Appartement,False,...,01427000AD0575,45.942301,4.770694,0.0,0.0,0.0,0.0,0.0,84.0,2345.238095
4,335040,2014-01-03,126000.0,01,283,OYONNAX,1100,29B RUE DE LA FORGE,Appartement,False,...,01283000AN0339,46.258411,5.640810,0.0,0.0,0.0,0.0,0.0,111.0,1135.135135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7810679,12600649,2022-12-30,125000.0,974,10,SAINT-BENOIT,97437,40 RUE BARTHELEMY HOAREAU,Maison,False,...,97410000BX0826,-21.090627,55.743567,0.0,0.0,0.0,194.0,0.0,252.0,496.031746
7810680,12603012,2022-12-30,204860.0,974,12,SAINT-JOSEPH,97480,216 RTE DE JEAN PETIT,Maison,False,...,97412000CE2489,-21.351724,55.633189,0.0,0.0,0.0,883.0,0.0,995.0,205.889447
7810681,12600629,2022-12-30,630000.0,974,11,SAINT DENIS,97400,1B RTE DES BAMBOUS - LE BRULE,Maison,False,...,97411000AV0057,-20.907399,55.444163,0.0,0.0,0.0,1290.0,0.0,1396.0,451.289398
7810682,12602012,2022-12-30,228560.0,974,11,SAINT DENIS,97490,16 CHE DES JAMBLONS,Appartement,False,...,97411000IB0232,-20.913288,55.492063,0.0,0.0,103.0,220.0,0.0,382.0,598.324607
7810683,12603294,2022-12-30,400000.0,974,11,SAINT DENIS,97490,1B RUE JOSEPH CARPAYE,Appartement,False,...,97411000DS0381,-20.895752,55.489366,0.0,0.0,0.0,0.0,0.0,140.0,2857.142857

In [16]:
departement.to_csv("immobilier_france.csv")

In [6]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7810684 entries, 0 to 7810683
Data columns (total 21 columns):
 #   Column                      Dtype
---  ------                      -----
 0   id_transaction              int32
 1   date_transaction            datetime64[ns]
 2   prix                        float64
 3   departement                 object
 4   id_ville                    int32
 5   ville                       object
 6   code_postal                 int32
 7   adresse                     object
 8   type_batiment               object
 9   vefa                        bool
 10  n_pieces                    int32
 11  surface_habitable           int32
 12  id_parcelle_cadastre        object
 13  latitude                    float64
 14  longitude                   float64
 15  surface_dependances         object
 16  surface_locaux_industriels  object
 17  surface_terrains_agricoles  object
 18  surface_terrains_sols       object
 19  surface_terrains_nature     object
 20  prix_m2                     float64
dtypes: bool(1), datetime64[ns](1), float64(4), int32(5), object(10)
memory usage: 1.0+ GB

In [7]:
transactions_77 = transactions[transactions['departement'] == "77"]

In [8]:
transactions_77

,id_transaction,date_transaction,prix,departement,id_ville,ville,code_postal,adresse,type_batiment,vefa,...,surface_habitable,id_parcelle_cadastre,latitude,longitude,surface_dependances,surface_locaux_industriels,surface_terrains_agricoles,surface_terrains_sols,surface_terrains_nature,prix_m2
5861618,10628657,2014-01-02,258150.0,77,335,CHAUCONIN-NEUFMONTIERS,77124,1 SEN DE LA LOGE,Maison,False,...,130,773350000B1521,48.981764,2.841230,{},{},{},{614},{},1985.769231
5861619,10628357,2014-01-02,117000.0,77,243,LAGNY-SUR-MARNE,77400,84 RUE SAINT DENIS,Appartement,False,...,29,77243000AL0043,48.879459,2.710152,{},{},{},{},{},4034.482759
5861620,10631677,2014-01-02,260000.0,77,335,CHAUCONIN-NEUFMONTIERS,77124,4 SEN DE LA LOGE,Maison,False,...,114,773350000B1516,48.982044,2.841364,{},{},{},{554},{},2280.701754
5861621,10626035,2014-01-02,215000.0,77,219,GUERARD,77580,5 RUE DU BOIS,Maison,False,...,60,772190000D2321,48.826927,2.950730,{},{},{},{1035},{},3583.333333
5861622,10618386,2014-01-02,185000.0,77,296,MOISSY-CRAMAYEL,77550,752E AV DE L'EUROPE,Appartement,False,...,86,77296000AM0671,48.628629,2.573929,"{0,0}",{},{},{},{},2151.162791
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6038564,9485625,2022-12-30,185000.0,77,108,CHELLES,77500,40 AV FRANCOIS MITTERRAND,Appartement,False,...,47,77108000CD0022,48.876612,2.598781,{0},{},{},{},{},3936.170213
6038565,9480641,2022-12-30,149900.0,77,390,ROISSY-EN-BRIE,77680,34 AV DE LA PIERRERIE,Appartement,False,...,53,77390000AI0028,48.794564,2.643199,"{0,0}",{},{},{},{},2828.301887
6038566,9482545,2022-12-30,240000.0,77,373,PONTAULT COMBAULT,77340,11 RUE GILBERT REY,Appartement,False,...,60,773730000D2625,48.782018,2.603489,{0},{},{},{},{},4000.000000
6038567,9490610,2022-12-31,300000.0,77,533,VULAINES-SUR-SEINE,77870,7E RUE DE LA BROSSE,Maison,False,...,115,77533000AI0160,48.432837,2.766011,{},{},{},"{538,11}",{},2608.695652
6038568,9468380,2022-12-31,105000.0,77,478,USSY-SUR-MARNE,77260,49 RUE DE CHANGIS,Appartement,False,...,42,774780000E0723,48.954392,3.069815,{},{},{},{1000},{},2500.000000

In [9]:
transactions.index=transactions["date_transaction"]

In [10]:
tf=transactions.loc["2014-01"]

In [11]:
tfk=tf[tf['departement'] == "35"]

In [12]:
tfk

,id_transaction,date_transaction,prix,departement,id_ville,ville,code_postal,adresse,type_batiment,vefa,...,surface_habitable,id_parcelle_cadastre,latitude,longitude,surface_dependances,surface_locaux_industriels,surface_terrains_agricoles,surface_terrains_sols,surface_terrains_nature,prix_m2
date_transaction,,,,,,,,,,,,,,,,,,,,,
2014-01-02,4830623,2014-01-02,50000.0,35,288,SAINT-MALO,35400,18 RUE MONTAGNE ST JOSEPH,Appartement,False,...,50,35288000VS0014,48.645452,-1.984703,{},{},{},{},{},1000.000000
2014-01-02,4826227,2014-01-02,357000.0,35,238,RENNES,35000,23 RUE LESAGE,Appartement,False,...,129,35238000BE0546,48.117227,-1.674441,{0},{},{},{},{},2767.441860
2014-01-02,4840520,2014-01-02,121000.0,35,238,RENNES,35000,35 BD MARBEUF,Appartement,False,...,62,35238000AI0026,48.109764,-1.705560,{},{},{},{},{},1951.612903
2014-01-02,4833510,2014-01-02,75000.0,35,127,GUIGNEN,35580,50 RUE GICQUEL,Maison,False,...,105,35127000XH0343,47.921452,-1.868707,{},{},{},{1179},{},714.285714
2014-01-02,4833296,2014-01-02,80000.0,35,339,TRANS-LA-FORET,35610,5371 LA PETITE ABBAYE,Maison,False,...,200,353390000A0648,48.507016,-1.605193,{},{},{26},{1032},{},400.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-01-31,4840518,2014-01-31,115886.0,35,238,RENNES,35700,24 RUE DE BRIZEUX,Appartement,True,...,22,35238000BD0034,48.118833,-1.672990,{},{},{},{},{},5267.545455
2014-01-31,4821935,2014-01-31,65000.0,35,238,RENNES,35000,3 RUE DESCARTES,Appartement,False,...,82,35238000BS0029,48.107079,-1.674046,{0},{},{},{},{},792.682927
2014-01-31,4822272,2014-01-31,40000.0,35,288,SAINT-MALO,35400,17 RUE DE L INDUSTRIE,Appartement,False,...,20,35288000AI0101,48.652767,-2.011987,{},{},{},{},{},2000.000000
2014-01-31,4823120,2014-01-31,316000.0,35,207,NOYAL-SUR-VILAINE,35530,5442 LA MOINERIE,Maison,False,...,193,352070000A2671,48.125878,-1.521516,{},{},{3852},{790},{},1637.305699
2014-01-31,4822657,2014-01-31,130000.0,35,53,CHANCE,35680,5064 A LA FALOTTERIE,Maison,False,...,85,350530000B0004,48.035407,-1.354430,{},{},{},{441},{},1529.411765

In [13]:
transactions.index = pd.to_datetime(transactions.index, format='%d/%m/%Y', errors='coerce')

In [19]:
import pandas as pd

# Supposons que votre DataFrame s'appelle transactions_df
# Assurez-vous que la colonne 'date' est au format date ou datetime

# Convertir la colonne 'date' en datetime si elle ne l'est pas déjà
transactions['date_transaction'] = pd.to_datetime(transactions['date_transaction'])

# Extrait l'année de la colonne 'date' et stocke-le dans une nouvelle colonne 'annee'
transactions['annee_mois'] = transactions['date_transaction'].dt.strftime('%Y-%m')

# Utilisez la méthode groupby pour regrouper les transactions par année
transactions_par_annee = transactions.groupby('annee_mois').size().reset_index(name='transactions_par_annee')

# La nouvelle colonne 'transactions_par_annee' contient le nombre de transactions pour chaque année
# Vous pouvez maintenant accéder à cette colonne dans votre DataFrame

In [30]:
transactions

,id_transaction,date_transaction,prix,departement,id_ville,ville,code_postal,adresse,type_batiment,vefa,...,latitude,longitude,surface_dependances,surface_locaux_industriels,surface_terrains_agricoles,surface_terrains_sols,surface_terrains_nature,prix_m2,annee,annee_mois
date_transaction,,,,,,,,,,,,,,,,,,,,,
2014-01-02,332948,2014-01-02,173020.0,01,202,LAGNIEU,1150,21 GR GRANDE RUE DE BULLIEZ,Maison,False,...,45.899056,5.354210,{},{},{},"{336,191}",{},2403.055556,2014,2014-01
2014-01-02,328900,2014-01-02,157500.0,01,451,VIRIAT,1440,1369 RTE DE STRASBOURG,Maison,False,...,46.236407,5.262935,{},{},{},"{1569,24}",{},1529.126214,2014,2014-01
2014-01-02,326170,2014-01-02,112000.0,01,365,SAINT-JEAN-SUR-VEYLE,1290,5174 SAINT JEAN SUR VEYLE,Maison,False,...,46.260087,4.918587,{},{},{220},{540},{},1435.897436,2014,2014-01
2014-01-02,328585,2014-01-02,197000.0,01,427,TREVOUX,1600,6346 MTE DES LILAS,Appartement,False,...,45.942301,4.770694,"{0,0}",{},{},{},{},2345.238095,2014,2014-01
2014-01-03,335040,2014-01-03,126000.0,01,283,OYONNAX,1100,29B RUE DE LA FORGE,Appartement,False,...,46.258411,5.640810,{},{},{},{},{},1135.135135,2014,2014-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-30,12600649,2022-12-30,125000.0,974,10,SAINT-BENOIT,97437,40 RUE BARTHELEMY HOAREAU,Maison,False,...,-21.090627,55.743567,{},{},{},{194},{},2155.172414,2022,2022-12
2022-12-30,12603012,2022-12-30,204860.0,974,12,SAINT-JOSEPH,97480,216 RTE DE JEAN PETIT,Maison,False,...,-21.351724,55.633189,{},{},{},{883},{},1829.107143,2022,2022-12
2022-12-30,12600629,2022-12-30,630000.0,974,11,SAINT DENIS,97400,1B RTE DES BAMBOUS - LE BRULE,Maison,False,...,-20.907399,55.444163,{},{},{},{1290},{},5943.396226,2022,2022-12
2022-12-30,12602012,2022-12-30,228560.0,974,11,SAINT DENIS,97490,16 CHE DES JAMBLONS,Appartement,False,...,-20.913288,55.492063,{0},{},{103},{220},{},3873.898305,2022,2022-12
2022-12-30,12603294,2022-12-30,400000.0,974,11,SAINT DENIS,97490,1B RUE JOSEPH CARPAYE,Appartement,False,...,-20.895752,55.489366,{},{},{},{},{},2857.142857,2022,2022-12

In [31]:
merged_df = pd.merge(transactions, transactions_par_annee, on='annee_mois', how='right')

In [38]:
merged_df.head(50)

,id_transaction,date_transaction,prix,departement,id_ville,ville,code_postal,adresse,type_batiment,vefa,...,longitude,surface_dependances,surface_locaux_industriels,surface_terrains_agricoles,surface_terrains_sols,surface_terrains_nature,prix_m2,annee,annee_mois,transactions_par_annee
0,332948,2014-01-02,173020.00,01,202,LAGNIEU,1150,21 GR GRANDE RUE DE BULLIEZ,Maison,False,...,5.354210,{},{},{},"{336,191}",{},2403.055556,2014,2014-01,42933
1,328900,2014-01-02,157500.00,01,451,VIRIAT,1440,1369 RTE DE STRASBOURG,Maison,False,...,5.262935,{},{},{},"{1569,24}",{},1529.126214,2014,2014-01,42933
2,326170,2014-01-02,112000.00,01,365,SAINT-JEAN-SUR-VEYLE,1290,5174 SAINT JEAN SUR VEYLE,Maison,False,...,4.918587,{},{},{220},{540},{},1435.897436,2014,2014-01,42933
3,328585,2014-01-02,197000.00,01,427,TREVOUX,1600,6346 MTE DES LILAS,Appartement,False,...,4.770694,"{0,0}",{},{},{},{},2345.238095,2014,2014-01,42933
4,335040,2014-01-03,126000.00,01,283,OYONNAX,1100,29B RUE DE LA FORGE,Appartement,False,...,5.640810,{},{},{},{},{},1135.135135,2014,2014-01,42933
5,330124,2014-01-03,156750.00,01,53,BOURG-EN-BRESSE,1000,15 RUE DE MONTHOLON,Appartement,False,...,5.210840,"{0,0}",{},{},{},{},1888.554217,2014,2014-01,42933
6,332844,2014-01-03,88000.00,01,283,OYONNAX,1100,29B RUE DE LA FORGE,Appartement,False,...,5.640810,{},{},{},{},{},846.153846,2014,2014-01,42933
7,335069,2014-01-03,49023.30,01,27,BALAN,1360,7 LOT AFU DE BARBAREL,Maison,False,...,5.097926,{},{},{},{1027},{},466.888571,2014,2014-01,42933
8,331955,2014-01-03,202500.00,01,352,ST ETIENNE-SUR-REYSSOUZE,1190,5112 AU MOIROUX,Maison,False,...,5.017710,{},{},"{930,73,53,1172}","{641,878,1737}",{},1716.101695,2014,2014-01,42933
9,332330,2014-01-03,68000.00,01,53,BOURG-EN-BRESSE,1000,10Z RUE EDGAR QUINET,Appartement,False,...,5.225693,{},{},{},{},{},1545.454545,2014,2014-01,42933
10,328680,2014-01-03,203000.00,01,142,DAGNEUX,1120,733C RTE DE STE CROIX,Maison,False,...,5.055253,{},{},{},{270},{},2255.555556,2014,2014-01,42933
11,333518,2014-01-03,145000.00,01,156,FARAMANS,1800,100 CHE DE LA COTE VOYANT,Maison,False,...,5.123846,{},{},{},{330},{},1647.727273,2014,2014-01,42933
12,333357,2014-01-03,163640.00,01,376,SAINT-MAURICE-DE-BEYNOST,1700,40 AV DES ILES,Appartement,False,...,4.977208,{0},{},{},{},{},1948.095238,2014,2014-01,42933
13,328419,2014-01-06,103000.00,01,160,FERNEY-VOLTAIRE,1210,70 RUE DE MEYRIN,Appartement,False,...,6.104149,{},{},{},{},{},3322.580645,2014,2014-01,42933
14,327649,2014-01-06,80000.00,01,283,OYONNAX,1100,12 RUE DE LATTRE DE TASSIGNY,Appartement,False,...,5.642869,{0},{},{},{},{},1230.769231,2014,2014-01,42933
15,326231,2014-01-06,190000.00,01,159,FEILLENS,1570,375 CHE DE VERRAIES,Maison,False,...,4.898364,{},{},{39},{1118},{},2000.000000,2014,2014-01,42933
16,328938,2014-01-06,242000.00,01,261,MONTHIEUX,1390,354 RUE DE LA CROIX,Maison,False,...,4.944417,{},{},{},"{99,667,76}",{},2220.183486,2014,2014-01,42933
17,327050,2014-01-06,177500.00,01,33,BELLEGARDE-SUR-VALSERINE,1200,23 RUE DE MUSSEL,Maison,False,...,5.816066,{0},{},{},"{619,52}",{},1479.166667,2014,2014-01,42933
18,333614,2014-01-06,415000.00,01,173,GEX,1170,111 RUE DE PARIS,Appartement,False,...,6.056970,{0},{},{},{},{},3547.008547,2014,2014-01,42933
19,334701,2014-01-06,107000.00,01,53,BOURG-EN-BRESSE,1000,18 RUE GEORGES GUYNEMER,Appartement,False,...,5.208606,{0},{},{},{},{},1320.987654,2014,2014-01,42933
20,331118,2014-01-06,430500.00,01,261,MONTHIEUX,1390,300 GR GRANDE RUE,Maison,False,...,4.940593,{},{},{},{1903},{},2460.000000,2014,2014-01,42933
21,329020,2014-01-06,165000.00,01,33,BELLEGARDE-SUR-VALSERINE,1200,10 RUE VIALA,Appartement,False,...,5.826308,{},{},{},{},{},1896.551724,2014,2014-01,42933
22,332146,2014-01-06,310000.00,01,192,IZERNORE,1580,15 IMP DES PINS,Maison,False,...,5.554562,{},{},{},{1424},{},2384.615385,2014,2014-01,42933
23,333007,2014-01-06,363800.00,01,339,SAINT-BERNARD,1600,947 CHE DU BOIS DE LYS,Maison,False,...,4.746478,{},{},{},{2096},{},2655.474453,2014,2014-01,42933
24,333556,2014-01-06,152000.00,01,31,BELLIGNAT,1100,16 RUE GUSTAVE FLAUBERT,Maison,False,...,5.633677,{},{},{},{470},{},1652.173913,2014,2014-01,42933
25,329256,2014-01-06,180230.00,01,355,SAINT-GENIS-SUR-MENTHON,1380,5013 LA TERRASSE,Maison,False,...,5.012925,{},{},"{70,743}","{755,34,190}",{},901.150000,2014,2014-01,42933
26,334213,2014-01-06,132500.00,01,74,CHALAMONT,1320,71 IMP DE LA BOURDONNIERE,Appartement,False,...,5.172874,{},{},{},{150},{},1540.697674,2014,2014-01,42933
27,330769,2014-01-06,680000.00,01,143,DIVONNE-LES-BAINS,1220,237 AV DES THERMES,Appartement,False,...,6.134868,{},{},{},{},{},5666.666667,2014,2014-01,42933
28,327631,2014-01-07,70000.00,01,34,BELLEY,1300,25 GR GRANDE RUE,Appartement,False,...,5.688117,{0},{},{},{},{},608.695652,2014,2014-01,42933
29,326209,2014-01-07,161400.00,01,249,MIRIBEL,1700,54 PAS DU LAVOIR,Appartement,False,...,4.952087,{},{},{},{},{},1698.947368,2014,2014-01,42933
30,334994,2014-01-07,195000.00,01,173,GEX,1170,283 RUE DES ABATTOIRS,Appartement,False,...,6.056211,{},{},{},{},{},1741.071429,2014,2014-01,42933
31,333681,2014-01-07,90000.00,01,53,BOURG-EN-BRESSE,1000,4 RUE GEN DELESTRAINT,Appartement,False,...,5.219917,{0},{},{},{},{},1475.409836,2014,2014-01,42933
32,326301,2014-01-07,8000.00,01,143,DIVONNE-LES-BAINS,1220,87 AV MARCEL ANTHONIOZ,Appartement,False,...,6.139886,{},{0},{},{},{},77.669903,2014,2014-01,42933
33,328709,2014-01-07,356500.00,01,244,MEXIMIEUX,1800,11 RUE DES MURGERES,Maison,False,...,5.200689,{},{},{},{2043},{},3565.000000,2014,2014-01,42933
34,335552,2014-01-07,94000.00,01,283,OYONNAX,1100,11 RUE DE LA PAILLETTE,Maison,False,...,5.627083,{},{},{},{605},{},839.285714,2014,2014-01,42933
35,327610,2014-01-07,240750.00,01,43,BEYNOST,1700,139 ALL DE LA POPONATE,Maison,False,...,4.997996,{},{},{},{614},{},2675.000000,2014,2014-01,42933
36,333950,2014-01-07,108500.00,01,53,BOURG-EN-BRESSE,1000,7 RUE DES GRAVES,Appartement,False,...,5.230645,{0},{},{},{},{},1669.230769,2014,2014-01,42933
37,326991,2014-01-08,50000.00,01,210,LELEX,1410,5091 LE MUISET,Appartement,False,...,5.946222,{0},{},{},{},{},2083.333333,2014,2014-01,42933
38,332108,2014-01-08,173000.00,01,264,MONTRACOL,1310,3 LOT LES FRENES,Maison,False,...,5.121318,{},{},{},{735},{},1922.222222,2014,2014-01,42933
39,330526,2014-01-08,206800.00,01,446,VILLENEUVE,1480,10 ALL DES MARGUERITES,Maison,False,...,4.832329,{},{},{},{624},{},2068.000000,2014,2014-01,42933
40,329383,2014-01-08,114000.00,01,4,AMBERIEU-EN-BUGEY,1500,29B RUE JULES FERRY,Appartement,False,...,5.342134,"{0,0}",{},{},{},{},2478.260870,2014,2014-01,42933
41,328270,2014-01-08,290000.00,01,4,AMBERIEU-EN-BUGEY,1500,4 CHE DE LA VEZE,Maison,False,...,5.378985,{},{},{},"{136,45,861}",{},1946.308725,2014,2014-01,42933
42,330640,2014-01-08,72000.00,01,407,SEYSSEL,1420,2 BD BONIVARD,Appartement,False,...,5.830868,{0},{},{},{},{},1220.338983,2014,2014-01,42933
43,327992,2014-01-08,205000.00,01,53,BOURG-EN-BRESSE,1000,1 AV ALPHONSE BAUDIN,Appartement,False,...,5.218639,{},{},{},{},{},1090.425532,2014,2014-01,42933
44,335151,2014-01-08,185950.00,01,244,MEXIMIEUX,1800,3 RUE DE PROVENCE,Maison,False,...,5.196459,{},{},{},{445},{},1936.979167,2014,2014-01,42933
45,326745,2014-01-08,247580.00,01,398,SAVIGNEUX,1480,18 ALL DU CHAMP CERISIER,Maison,False,...,4.841220,{},{},{},{801},{},2250.727273,2014,2014-01,42933
46,335526,2014-01-08,319063.55,01,399,SEGNY,1170,663 RTE BLANCHE,Appartement,True,...,6.075187,{0},{},{},{},{},4692.111029,2014,2014-01,42933
47,329244,2014-01-09,381270.90,01,376,SAINT-MAURICE-DE-BEYNOST,1700,36 RTE DE GENEVE,Appartement,False,...,4.980655,"{0,0}",{},{},{},{},3701.659223,2014,2014-01,42933
48,326135,2014-01-09,189500.00,01,33,BELLEGARDE-SUR-VALSERINE,1200,940 RTE DE VOUVRAY,Appartement,False,...,5.811630,{0},{},{},{},{},2828.358209,2014,2014-01,42933
49,328640,2014-01-09,188500.00,01,4,AMBERIEU-EN-BUGEY,1500,36 AV DE LA LIBERATION,Maison,False,...,5.335784,{},{},{},{761},{},3040.322581,2014,2014-01,42933

In [37]:
transactions_77 = merged_df[merged_df['departement'] == "77"]
transactions_77

,id_transaction,date_transaction,prix,departement,id_ville,ville,code_postal,adresse,type_batiment,vefa,...,longitude,surface_dependances,surface_locaux_industriels,surface_terrains_agricoles,surface_terrains_sols,surface_terrains_nature,prix_m2,annee,annee_mois,transactions_par_annee
31829,10628657,2014-01-02,258150.0,77,335,CHAUCONIN-NEUFMONTIERS,77124,1 SEN DE LA LOGE,Maison,False,...,2.841230,{},{},{},{614},{},1985.769231,2014,2014-01,42933
31830,10628357,2014-01-02,117000.0,77,243,LAGNY-SUR-MARNE,77400,84 RUE SAINT DENIS,Appartement,False,...,2.710152,{},{},{},{},{},4034.482759,2014,2014-01,42933
31831,10631677,2014-01-02,260000.0,77,335,CHAUCONIN-NEUFMONTIERS,77124,4 SEN DE LA LOGE,Maison,False,...,2.841364,{},{},{},{554},{},2280.701754,2014,2014-01,42933
31832,10626035,2014-01-02,215000.0,77,219,GUERARD,77580,5 RUE DU BOIS,Maison,False,...,2.950730,{},{},{},{1035},{},3583.333333,2014,2014-01,42933
31833,10618386,2014-01-02,185000.0,77,296,MOISSY-CRAMAYEL,77550,752E AV DE L'EUROPE,Appartement,False,...,2.573929,"{0,0}",{},{},{},{},2151.162791,2014,2014-01,42933
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7798120,9485625,2022-12-30,185000.0,77,108,CHELLES,77500,40 AV FRANCOIS MITTERRAND,Appartement,False,...,2.598781,{0},{},{},{},{},3936.170213,2022,2022-12,50995
7798121,9480641,2022-12-30,149900.0,77,390,ROISSY-EN-BRIE,77680,34 AV DE LA PIERRERIE,Appartement,False,...,2.643199,"{0,0}",{},{},{},{},2828.301887,2022,2022-12,50995
7798122,9482545,2022-12-30,240000.0,77,373,PONTAULT COMBAULT,77340,11 RUE GILBERT REY,Appartement,False,...,2.603489,{0},{},{},{},{},4000.000000,2022,2022-12,50995
7798123,9490610,2022-12-31,300000.0,77,533,VULAINES-SUR-SEINE,77870,7E RUE DE LA BROSSE,Maison,False,...,2.766011,{},{},{},"{538,11}",{},2608.695652,2022,2022-12,50995
7798124,9468380,2022-12-31,105000.0,77,478,USSY-SUR-MARNE,77260,49 RUE DE CHANGIS,Appartement,False,...,3.069815,{},{},{},{1000},{},2500.000000,2022,2022-12,50995

In [42]:
filtre1 = transactions.ville = "Rennes"
filtre2 = transactions.departement="35"
filtre3 = transactions.annee="2014"

In [52]:
rennes = transactions[transactions["date_transaction"]=="2014-01-02"]

In [54]:
rennes

,id_transaction,date_transaction,prix,departement,id_ville,ville,code_postal,adresse,type_batiment,vefa,...,latitude,longitude,surface_dependances,surface_locaux_industriels,surface_terrains_agricoles,surface_terrains_sols,surface_terrains_nature,prix_m2,annee,annee_mois
date_transaction,,,,,,,,,,,,,,,,,,,,,
2014-01-02,332948,2014-01-02,173020.0,35,202,Rennes,1150,21 GR GRANDE RUE DE BULLIEZ,Maison,False,...,45.899056,5.354210,{},{},{},"{336,191}",{},2403.055556,2014,2014-01
2014-01-02,328900,2014-01-02,157500.0,35,451,Rennes,1440,1369 RTE DE STRASBOURG,Maison,False,...,46.236407,5.262935,{},{},{},"{1569,24}",{},1529.126214,2014,2014-01
2014-01-02,326170,2014-01-02,112000.0,35,365,Rennes,1290,5174 SAINT JEAN SUR VEYLE,Maison,False,...,46.260087,4.918587,{},{},{220},{540},{},1435.897436,2014,2014-01
2014-01-02,328585,2014-01-02,197000.0,35,427,Rennes,1600,6346 MTE DES LILAS,Appartement,False,...,45.942301,4.770694,"{0,0}",{},{},{},{},2345.238095,2014,2014-01
2014-01-03,335040,2014-01-02,126000.0,35,283,Rennes,1100,29B RUE DE LA FORGE,Appartement,False,...,46.258411,5.640810,{},{},{},{},{},1135.135135,2014,2014-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-30,12600649,2014-01-02,125000.0,35,10,Rennes,97437,40 RUE BARTHELEMY HOAREAU,Maison,False,...,-21.090627,55.743567,{},{},{},{194},{},2155.172414,2022,2022-12
2022-12-30,12603012,2014-01-02,204860.0,35,12,Rennes,97480,216 RTE DE JEAN PETIT,Maison,False,...,-21.351724,55.633189,{},{},{},{883},{},1829.107143,2022,2022-12
2022-12-30,12600629,2014-01-02,630000.0,35,11,Rennes,97400,1B RTE DES BAMBOUS - LE BRULE,Maison,False,...,-20.907399,55.444163,{},{},{},{1290},{},5943.396226,2022,2022-12
2022-12-30,12602012,2014-01-02,228560.0,35,11,Rennes,97490,16 CHE DES JAMBLONS,Appartement,False,...,-20.913288,55.492063,{0},{},{103},{220},{},3873.898305,2022,2022-12
2022-12-30,12603294,2014-01-02,400000.0,35,11,Rennes,97490,1B RUE JOSEPH CARPAYE,Appartement,False,...,-20.895752,55.489366,{},{},{},{},{},2857.142857,2022,2022-12

In [ ]:
#train = df[df.index.year <= 2014]   
#test = df[df.index.year >= 2015]